https://chatgpt.com/share/670dfd68-4dc4-8003-8682-89a781a30526 <br>
1. Inquiry About a YouTube Video:

You initially asked about a YouTube video that discussed Fisher's Tea Experiment and how to analyze it. <br>
2. Understanding Random Seed:

We explored the concept of a random seed in the context of bootstrapping, discussing how setting a seed (like 42 or 5) ensures reproducibility by generating the same bootstrapped sample every time the code is run.<br>
3. Using Multiple Random Seeds:

You inquired about how to use different random seeds for generating multiple bootstrapped samples. We clarified that you could call the bootstrap function multiple times, each with a different random seed.<br>
4. One-tailed vs. Two-tailed Tests:

We examined whether the test in your code was one-tailed or two-tailed. You identified it as a two-tailed test, and we discussed how to adjust the code to perform a one-tailed test by removing the absolute value function. This change affects the interpretation of the hypothesis test and how we calculate the p-value.<br>
5. Calculating the p-value:

We discussed the formula for calculating the p-value in the context of hypothesis testing and how to interpret its significance relative to the null hypothesis.
Interpreting the p-value:

You noted that the p-value (0.5568) indicates the proportion of times the statistic is greater than or equal to the observed statistic, suggesting that students’ correct guesses were likely due to chance.
Visualization of Bootstrapped Samples:

You requested a visualization to help understand the distribution of bootstrapped proportions. I provided the code to visualize this, including a histogram of bootstrapped proportions and a line indicating the observed proportion.<br>
6. Confidence Intervals and One-tailed Tests:

We discussed whether to include confidence intervals in a one-tailed test and concluded that it is typically unnecessary.
Conclusion on the Null Hypothesis:

You crafted a conclusion stating that the p-value of 0.5568 is high, indicating insufficient evidence to reject the null hypothesis, meaning the difference in taste could likely be attributed to chance rather than the ability to distinguish between the pouring orders.
Final Statements on Hypotheses:

You articulated the null and alternative hypotheses clearly, affirming that there is no difference in taste when milk is poured before or after tea, versus the claim that there is a difference.

**1. The "first pre-lecture video" (above) describes hypothesis testing as addressing "an idea that can be tested", and the end of the video then discusses what our actual intended purpose in setting up a null hypothesis is. What is the key factor that makes the difference between ideas that can, and cannot be examined and tested statistically? What would you describe is the key "criteria" defining what a good null hypothesis is? And what is the difference between a null hypothesis and an alternative hypothesis in the context of hypothesis testing? Answer these questions with concise explanations in your own words.** <br>
The key different that distinguish ideas that can and cannot be proven statistically is the data available for tesing. <br>
A good null hypothesis is the hypothesis that is set to be disproven. <br>
Null hypothesis states that there's no difference between the variables being examined, or it is a hypothetical value that is said to be true for the parameter. And it is usually set up to be disproven. An alternative hypothesis states the opposite of null hypothesis.

**2. Towards the end of the "first pre-lecture" video (above) it is stated that, "It is important to note that outcomes of tests refer to the population parameter, rather than the sample statistic! As such, the result that we get is for the population." In terms of the distinctions between the concepts of  𝑥𝑖
 's,  𝑥¯,  𝜇, and  𝜇0, how would you describe what the sentence above means? Explain this concisely in your own words for a "non-statsitical" audience, defining the technical statistical terminology you use in your answer.**
 
𝑥𝑖's represent the individual data points in my sample, 𝑥¯ is the mean (average value) of my sample, 𝜇 is the actual mean of the population, and 𝜇0 is the hypothetical mean that we are testing against. The video emphasizes that from the individual data points (𝑥𝑖's), we can calculate the characteristic of the sample, which is 𝑥¯ (x-bar). By analyzing this sample mean, we can make inferences not just about the sample itself but about the population from which it was drawn. Specifically, we can determine whether the true population mean 𝜇 is likely to differ from the hypothetical mean 𝜇0 based on our sample data. Thus, the outcome of the test is meant to tell us something about the population, not just the sample.

**3. The second "Pre-lecture" video (above) explains that we "imagine a world where the null hypothesis is true" when calculating a p-value? Explain why this is in your own words in a way that makes the most sense to you.**

Because we have to assume the null hypothesis is true, it acts as a baseline or point of reference for comparison. Given that point, when finding the p-value, we will check if the test statistic is in sync with the hypothetical statistics. This leads us to either reject the null hypothesis or accept it based on how likely or unlikely our observed data is under the assumption that the null hypothesis holds.

**4. The second "Pre-lecture" video (above) describes suggest that a smaller p-value makes the null hypothesis look more ridiculous. Explain why this is in your own words in a way that makes the most sense to you, clarifying the meaning of any technical statistical terminology you use in your answer.**


We start by assuming the null hypothesis is true. When we calculate the p-value, a small value indicates that the observed test statistic is far from the hypothetical mean (often implying a large deviation from what we would expect if the null were true). A smaller p-value suggests that the observed data is unlikely to occur if the null hypothesis were correct. This makes the null hypothesis seem less plausible or "more ridiculous" because the actual data differs significantly from what the null hypothesis predicts.


**Question 7. In the second half of the "first pre-lecture video" the concept of a "one sided" (or "one tailed") test is introduced in contrast to a "two sided" (or "two tailed") test. Work with a ChatBot to adjust the code from "Demo II of the Week 5 TUT" (which revisits the "Vaccine Data Analysis Assignment" from Week 04 HW "Question 8") in order to compute a p-value for a "one sided" (or "one tailed") hypothesis test rather than the "two sided" (or "two tailed") version it provides. Describe (perhaps with the help of your ChatBot) what changed in the code; how this changes the interpretation of the hypothesis test; and whether or not we should indeed expect the p-value to be smaller in the "one tailed" versus "two tailed" analysis.**

To change from a 2 tailed test to 1 sided, we eliminate the absolute function when calculating p-value. In 2 tailed test, we check if the p value is more extreme From <br>
**p_value_two_tailed = np.mean(np.abs(bootstrapped_proportions - observed_proportion) >= np.abs(0.5 - observed_proportion))** <br>
to **p_value_one_tailed = np.mean(bootstrapped_proportions >= observed_proportion)** <br>
This changes the interpretation of the hypothesis test, because instead of comparing the test statistics with the hypothetical one for both direction, now we only check for one direction (whether it is < or >=) We should expect the p value to be smaller in 1 tailed test because the p value this time represent the probability of extreme results occurring only one side.




**Question 8.Clarity of your documentation, code, and written report**


**Problem Introduction**
1. Relationship between this experiment and the original with Fisher and Bristol <br>
The original experiment is only based on the taste of one person, Bristol, but the experiment carried out by STA130 students are based on taste of 80 students, so there would be more variance in the statistics. Both experiments are similar in the sense that they want to test if the person can actually distinguish the taste of tea if the milk is poured in first or after, or they only guess it correctly by chance <br>

2. Statements of the Null Hypothesis and Alternative hypothesis
Null hypothesis: There is no difference in taste when the milk is poured into the cup before or after the tea. Alternative hypothesis: There is a difference in taste when the milk is poured into the cup before or after the tea.




**Quantitative Analysis** <br>
Methodology Code and Explanations <br>
(if needed/optional) Supporting Visualizations

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Set random seed for reproducibility
np.random.seed(42)

# Set parameters
n = 80  # total number of students
k = 49  # number of students who guessed correctly
observed_proportion = k / n
alpha = 0.05  # significance level

# Bootstrapping
number_of_simulations = 10000
bootstrapped_proportions = np.zeros(number_of_simulations)

# Create an array with the outcomes: 1 for correct guesses, 0 for incorrect guesses
data = np.array([1] * k + [0] * (n - k))

# Perform bootstrapping
for i in range(number_of_simulations):
    # Sample with replacement from the original data
    sample = np.random.choice(data, size=n, replace=True)
    # Calculate the proportion of correct guesses in the bootstrap sample
    bootstrapped_proportions[i] = np.mean(sample)

# Calculate the p-value
# Count how many bootstrap proportions are greater than or equal to the observed proportion
p_value = np.mean(bootstrapped_proportions >= observed_proportion)

# Output results
print(f"Observed Proportion: {observed_proportion}")
print(f"P-value: {p_value}")

# Visualization of the bootstrap distribution
plt.hist(bootstrapped_proportions, bins=30, color='lightblue', edgecolor='black')
plt.axvline(observed_proportion, color='red', linestyle='dashed', linewidth=2, label=f'Observed Proportion: {observed_proportion}')
plt.title('Bootstrapped Proportions Distribution')
plt.xlabel('Proportion')
plt.ylabel('Frequency')
plt.legend()
plt.show()


Observed Proportion: 0.6125
P-value: 0.5568


**Findings and Discussion** <br>
Conclusion regarding the Null Hypothesis

The p-value is 0.5568, which is a high value, meaning that 55.68% of the time, the proportion of the students guessing the difference in the tea correctly is by chance, not because they can tell the difference. Since this p-value is greater than the observed statistic (0.6125), and it is much larger than the typical significance level (α = 0.05) we cannot reject the null hypothesis that there is no difference in the tea pouring order, as the evidence is not strong or extreme enough to suggest otherwise.